import React from 'react';
import { BarChart3, TrendingUp, Sparkles, Layers, ShieldCheck, Globe, Zap, Cpu, ArrowUpRight } from 'lucide-react';

export default function FeaturesSection() {
  const features = [
    {
      icon: BarChart3,
      title: 'Sentiment Analysis',
      desc: 'Multilingual neural classification detecting positive, neutral, and critical sentiment across English, Hindi, Hinglish, emojis and slang with guaranteed 100% mathematical balance.',
      badge: 'Multilingual NLP',
      accentColor: '#10b981'
    },
    {
      icon: TrendingUp,
      title: 'Trend Tracking',
      desc: 'Real-time observation of conversation velocity, volume shifts, and emerging public opinion patterns grounded strictly in real social data.',
      badge: 'Velocity',
      accentColor: '#38bdf8'
    },
    {
      icon: Sparkles,
      title: 'AI Insights',
      desc: 'Synthesized executive summaries generated by Google Gemini that extract actionable takeaways without hallucinations or disconnected claims.',
      badge: 'Gemini AI',
      accentColor: '#c084fc'
    },
    {
      icon: Layers,
      title: 'Topic Analysis',
      desc: 'Dynamic aspect extraction identifying core product, brand, or person domains (e.g., Taste, Battery, Pricing, Camera) tailored uniquely to every subject.',
      badge: 'Dynamic Domains',
      accentColor: '#818cf8'
    }
  ];

  return (
    <section id="features" className="features-section">
      <div className="features-container">
        
        <div className="section-header-centered">
          <div className="section-badge-center">
            <span className="section-badge-sparkle">✦</span>
            <span>CAPABILITIES</span>
          </div>
          <h2 className="section-title-large">Engineered for Deep Social Clarity</h2>
          <p className="section-subtitle-text">
            Soci-Eye transforms noisy unstructured social discussions into structured, high-signal intelligence for creators, analysts, and founders.
          </p>
        </div>

        <div className="features-grid">
          {features.map((item, idx) => {
            const Icon = item.icon;
            return (
              <div key={idx} className="feature-card glass-panel">
                <div className="feature-ambient-glow" style={{ background: `radial-gradient(circle, ${item.accentColor}20 0%, transparent 70%)` }}></div>
                
                <div className="feature-top-row">
                  <div className="feature-icon-bubble" style={{ color: item.accentColor, borderColor: `${item.accentColor}35`, backgroundColor: `${item.accentColor}12` }}>
                    <Icon size={22} />
                  </div>
                  <span className="feature-badge">{item.badge}</span>
                </div>

                <h3 className="feature-title">{item.title}</h3>
                <p className="feature-desc">{item.desc}</p>
                
                <div className="feature-card-footer">
                  <span className="feature-learn-more" style={{ color: item.accentColor }}>
                    <span>Explore capability</span>
                    <ArrowUpRight size={13} />
                  </span>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
}
